FROM debian
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y git
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt install -y pipx && pipx ensurepath
RUN apt install -y python3-tk && apt install -y python3-opencv
ENTRYPOINT echo "Dependencias básicas instaladas"